apiVersion: apps/v1
kind: Deployment
metadata:
  name: actor-service
  labels:
    app: actor-service
    app.kubernetes.io/name: actor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actor-service
  template:
    metadata:
      labels:
        app: actor-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "actor-service"
        dapr.io/app-port: "3000"
        dapr.io/log-level: "debug"
        dapr.io/log-as-json: "true"
        dapr.io/sidecar-liveness-probe-delay-seconds: "5"
        dapr.io/sidecar-liveness-probe-timeout-seconds: "10"

    spec:
      containers:
      - name: app
        image: actor-service  # EDIT HERE: Replace the image nmae with [docker registry]/demo_actor:latest
        command: ["uvicorn"]
        args: ["--port", "3000", "--reload-dir", "/app", "demo_actor_service:app"]
        ports:
        - containerPort: 3000